#! /usr/bin/perl -w

use strict;

usage () if !@ARGV;
(print "$ARGV[0]: chdir: $!\n"), usage () if !chdir ($ARGV[0]);

sub usage {
    print <<EOF;
cleanup, cleans up extra files in submission directories.

usage: cleanup HWDIR
where HWDIR is a directory whose subdirectories contain grade.txt files
in the format produced by the submit script.

Only subdirectories whose names are entirely alphanumeric and contain
a grade.txt file are cleaned.  Other files and directories are unaffected.
EOF
    exit 1;
}

for my $group (grep (/^[[:alnum:]]+$/, glob ('*'))) {
    -e "$group/grade.txt" or next;

    print "Cleaning $group...\n";
    system ("rm -rf $group/pintos");
    system ("rm -f $group/*~");
}
