#!/bin/bash
#
# This script downloads the bibtex file for group 'pintos' (6404) from citeulike.org
# To add a reference, simply post it to citeulike and make sure it's included 
# in group 'pintos'
#
# To run this script, you need to have your cookies stored in a file called "citeulikecookies.txt"
#
/bin/mv -f sigcse2009.bib sigcse2009.bib.old
wget -O _sigcse2009.bib \
    --load-cookies citeulikecookies.txt \
    'http://www.citeulike.org/bibtex/group/6404?do_username_prefix=0&key_type=4'

cat - _sigcse2009.bib > sigcse2009.bib << EOF
%
% This file is automatically generated by citeulike.org
%
EOF
/bin/rm -rf _sigcse2009.bib

