#!/bin/env python3

import sys

m = {}
f = open(sys.argv[1])
lines = f.readlines()
minTime = 2 ** 64
maxTime = 0

for i in range(1,len(lines)):
	prev = lines[i-1].split()
	curr = lines[i].split()
	if "idle" == prev[0]:
		continue
	if "main" == prev[0]:
		continue
	if "0)" == prev[2]:
		continue
	if "-1)" == prev[2]:
		continue
	process = prev[0] + " " + prev[1] + " " + prev[2]
	if "-1" != prev[6] and "-1" != curr[6]:
		s = int(prev[6])
		e = int(curr[6])
	elif "-1" != prev[6] and "-1" != curr[8]:
		s = int(prev[6])
		e = int(curr[8])
	else:
		# Probably prev. exited, current sched.
		continue
	if e > maxTime:
		maxTime = e
	if s < minTime:
		minTime = s
	if process in m:
		m[process] += [[s, e]]
	else:
		m[process]  = [[s, e]]

if maxTime - minTime > 1500:
	width = 5 / (maxTime - minTime)
else:
	width = 7 / (maxTime - minTime)

print("\\begin{ganttchart}[x unit=" + str(width) + "in,bar/.append style={fill=black}]{" + str(minTime) + "}{" + str(maxTime) + "}")
for process in m:
	label = False
	for record in m[process]:
		if False == label:
			print("\ganttbar{" + process + "}{" + str(record[0]) + "}{" + str(record[1]) + "}")
			label = True
		else:
			print("\ganttbar{}{" + str(record[0]) + "}{" + str(record[1]) + "}")
	print("\\\\")
print("\end{ganttchart}")
